/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./templates/**/*.html"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#fd81a8",
        "inverse-surface": "#faf8ff",
        "on-error": "#490013",
        "on-primary-fixed-variant": "#430076",
        "secondary-dim": "#50ebd5",
        "tertiary-fixed": "#ff8eb0",
        "inverse-primary": "#842cd3",
        "on-secondary-fixed": "#004840",
        "inverse-on-surface": "#4d556b",
        "surface-container-high": "#141f38",
        "primary-fixed": "#c284ff",
        "surface": "#060e20",
        "secondary": "#62fae3",
        "surface-bright": "#1f2b49",
        "surface-dim": "#060e20",
        "on-background": "#dee5ff",
        "on-primary-container": "#360061",
        "on-secondary-container": "#dcfff7",
        "surface-container-highest": "#192540",
        "tertiary-dim": "#f0779d",
        "surface-container": "#0f1930",
        "background": "#060e20",
        "outline": "#6d758c",
        "on-secondary-fixed-variant": "#00675c",
        "on-tertiary-fixed": "#380018",
        "primary-container": "#c284ff",
        "error-container": "#a70138",
        "surface-container-low": "#091328",
        "on-tertiary-fixed-variant": "#701039",
        "outline-variant": "#40485d",
        "on-tertiary-container": "#59002a",
        "on-secondary": "#005c52",
        "on-tertiary": "#6a0934",
        "on-primary-fixed": "#000000",
        "primary-dim": "#9c48ea",
        "surface-tint": "#cc97ff",
        "secondary-fixed": "#62fae3",
        "on-surface": "#dee5ff",
        "primary-fixed-dim": "#b971ff",
        "primary": "#cc97ff",
        "surface-container-lowest": "#000000",
        "on-primary": "#47007c",
        "on-error-container": "#ffb2b9",
        "error": "#ff6e84",
        "secondary-container": "#006b5f",
        "tertiary": "#ff97b5",
        "tertiary-fixed-dim": "#f67ca3",
        "surface-variant": "#192540",
        "on-surface-variant": "#a3aac4",
        "error-dim": "#d73357",
        "secondary-fixed-dim": "#50ebd5",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
        manrope: ["Manrope"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
